### PR TITLE
Audio script

### PR DESCRIPTION
**Pull request by FoggyTheRebelGod**
Sorry about the multiple commits.  I wasn't sure what was going on.  I actually put that in a couple days ago but wasn't sure how to add it, but I think I got it right now.

### CODE REVIEW

**Comment by FoggyTheRebelGod** [comment]
AAAAAAAAAA my stupid example script broke the camera!  I had to delete it to get the program to run...  

T_T

**Comment by OneHoopyFrood** [comment]
Don't worry! This is what branches are for! You can always do `git checkout main` and get back to a clean state 😄

**Comment by OneHoopyFrood** [comment]
Aye phixd et. 🤪 Ready for merge!

**Review by OneHoopyFrood — APPROVED** [review]

**Review by OneHoopyFrood — APPROVED** [review]

**Comment by OneHoopyFrood** [comment]
For context, I just had to make sure the sounds were copied during the build process, and add some wrapping around the code you had there so that it wasn't attempting to reference values in the global scope, which weren't actually there.

**Comment by FoggyTheRebelGod** [comment]
How am I gonna learn to code if you just fix everything for me?

**Pull request merged**
